repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.7.2
  hooks:
    # Run the linter.
    - id: ruff
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.13.0 # Asegúrate de usar la última versión de Mypy
  hooks:
    - id: mypy
      args: ["--strict"]  # Activa el modo estricto de Mypy