version: '3.9'
services:
  proyecto_rag_service:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: proyecto_rag_container
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - PORT=8501
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    stdin_open: true  # Permite mantener la terminal abierta
    tty: true         # Necesario para un shell interactivo
    command: ['streamlit', 'run', 'main_app.py']