FROM continuumio/miniconda3
# Actualizar paquetes e instalar dependencias necesarias para compilación
RUN apt-get update && apt-get install -y \
    gcc \
    g++ \
    make \
    libffi-dev \
    libssl-dev \
    libbz2-dev \
    libsqlite3-dev \
    zlib1g-dev \
    && apt-get clean
# Establece la variable de entorno para no generar archivos .pyc
ENV PYTHONDONTWRITEBYTECODE 1

# Establece la variable de entorno para no usar buffer en stdout y stderr
ENV PYTHONUNBUFFERED 1

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo requirements.txt en el contenedor
COPY environment_container.yml /app/
# Instala las dependencias desde el archivo requirements.txt
RUN conda env create -f environment_container.yml -y

RUN echo "source /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc \
    && echo "conda activate environment_proyecto_aplicado" >> ~/.bashrc

RUN python -m spacy download en_core_web_sm

# Copia toda la aplicación en el contenedor
COPY . /app/

