data_ground_truth = [
    {
        "question": "What type of notice might you receive for serious food safety problems?",
        "context": "by when. Usually, you’re responsible for conﬁrming these improvements\nhave been made.\nFor serious food safety problems you may be sent a ‘notice’. The notice can\ninclude banning you from using certain equipment or processes until include a:\n• Hygiene Improvement Notice\n• Hygiene Emergency Prohibition Notices - banning you from using certain\nequipment or following certain processes\nAppeals\nYour letter or notice should tell you how you can appeal a decision by an\ninspector. —\nFood hygiene\n(/food-safety-your-responsibilities/food-hygiene)\n—\nFood inspections—\nReport a food safety incident\n(/food-safety-your-responsibilities/report-a-food-safety-incident)\n— improvements have been made. Your business will be revisited to make\nsure you have followed the improvements in the notice. Example notices\ninclude a:\n• Hygiene Improvement Notice",
        "reference": "Hygiene Improvement Notice or Hygiene Emergency Prohibition Notices",
    },
    {
        "question": "What bacteria cause serious health problems according to food safety guidelines?",
        "context": "cause serious health problems are:\n• E.coli O157 and campylobacter (http://www.food.gov.uk/foodindustry/\nguidancenotes/hygguid/ecoliguide)\n• salmonella, especially with the storage and handling of eggs\nFood hygiene training when inspected, be able to show where the food contact materials came\nfrom\nBacteria and food poisoning\nTo keep food safe from bacteria, you should follow HACCP. Bacteria that\ncause serious health problems are: Food safety - your\nresponsibilities\nFood hygiene\nPart of complying with food safety is managing food hygiene (http://\nwww.food.gov.uk/foodindustry/regulation/hygleg/hyglegresources/sfbb/).\nHazard Analysis and Critical Control Point (HACCP)\nplan (/food-safety-your-responsibilities)\n—\nFood hygiene—\nFood inspections\n(/food-safety-your-responsibilities/food-inspections)\n—\nReport a food safety incident\n(/food-safety-your-responsibilities/report-a-food-safety-incident)\n—",
        "reference": "E.coli O157 and campylobacter, salmonella",
    },
    {
        "question": "What percentage of farm-grown ingredients must be organic for a retailer to label products as 'organic'?",
        "context": "Food labelling and packaging\nOrganic food\nIf you’re a retailer, you can label products ‘organic’ as long as:\n• at least 95% of the farm-grown ingredients are organic\n• you sell direct to customers in your shop\nOrganic certiﬁcation bodies) if you produce or prepare organic food and you want to sell or label it\nas organic.\nContents\nOverview\n(/food-labelling-and-packaging)\n—\nFood labelling - what you must show\n(/food-labelling-and-packaging/food-labelling-what-you-must-show)\n— Nutrition, health claims and supplement labelling\n(/food-labelling-and-packaging/nutrition-health-claims-and-supplement-\nlabelling)\n—\nOrganic food— allow annual and random inspections\nYou’ll also have to follow the rules for labelling organic products (/guidance/\norganic-food-labelling-rules).\nYou can check how food labelling rules are enforced (/guidance/food-labelling-",
        "reference": "At least 95%",
    },
    {
        "question": "What are the exceptions for small businesses regarding nutrition labelling on pre-packed products?",
        "context": "technical-guidance-on-nutrition-labelling) for all pre-packed products unless both\nof the following apply:\n• you’re a small business with under 10 employees and a turnover of less\nthan £1.4 million Food labelling and packaging\nNutrition, health claims and supplement\nlabelling\nNutrition labelling\nYou must follow nutrition labelling information rules (/government/publications/—\nFood and drink warnings\n(/food-labelling-and-packaging/food-and-drink-warnings)\n—\nNutrition, health claims and supplement labelling—\nOrganic food\n(/food-labelling-and-packaging/organic-food)\n— Nutrition and health claims\nYou have to follow certain rules if you want to make a nutrition claim (/\ngovernment/publications/nutrition-legislation-information-sources) (for example,",
        "reference": "Small businesses with under 10 employees and a turnover of less than £1.4 million that supply either direct to consumers or to local retailers within their county, their neighbouring county, or up to 30 miles from their county boundary are exempt from following nutrition labelling information rules for all pre-packed products.",
    },
    {
        "question": "Factoid question: What percentage of water added to a meat product requires the information to be included in the product's name?",
        "context": "You must tell the consumer if you add water to a meat product or preparation\nthat makes up more than 5% of its weight.\n You only need to do this if the meat product or preparation looks like a cut,\njoint, slice, portion or carcase. Products containing meat\n These are foods where meat is an ingredient, even if the other ingredient is 5%\nwater.\nA product containing meat also includes foods containing multiple ingredients, Types of meat products—\nProducts containing meat—\nTypes of meat you can’t sell—\nProducts with added water—\nFormed foods—\nAdded proteins—\nMinced meat—\nDate of freezing—\nReserved descriptions—\nPenalties—\nMeat labels—water’.\nFormed foods\nYou must tell the consumer if a food product looks like a whole piece of meat\nbut is made up of 2 or more separate pieces.\nPut the words ‘formed meat’ next to the name of the product.\nThis applies to products that:",
        "reference": "More than 5%",
    },
]
